spring.application.name=demo
spring.datasource.url=jdbc:postgresql://db.uqkhqkswphxzzlftghpm.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Root@123sharan
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect